### PR TITLE
Some things from the Rewrite Tweaks addon.

### PR DESCRIPTION
**Pull request by Dodobro**

### CODE REVIEW

**Review by francodml — CHANGES_REQUESTED** [review]
Move this to an exterior module. use `ENT:AddHook("OnTakeDamage", "HADS", func)` instead

**Review by francodml — CHANGES_REQUESTED** [review]
dem changes i said on discord

**Comment by francodml** [comment]
I'm gonna merge this and apply the requested changes myself. Thanks Dodo for contributing to science

**Review by francodml — APPROVED** [review]

**Comment by Dodobro** [comment]
love you

**Pull request merged**
